server:
  port: 8200

# Eureka server url
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: usuario-ms
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.8:3306/usuariodb?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: root
  #boot:
  #  admin:
  #    client:
  #      url: http://eureka:8761/admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
