# Default port for Eureka server
server:
  port: 8761
# Eureka server name
spring:
  application:
    name: eureka-server
  #boot:
  #  admin:
  #    context-path: /admin
# We are going to set the following attributes to false, because by 
#default Eureka registers itself as a client
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  